# ワークフロー名
name: tiktok_api
on:
  schedule:
    # 定期実行する時間・・・①
    - cron: '0 0-23 * * *'

jobs:
  build:
    # Ubuntuの最新版環境内で処理を実行することを指定
    runs-on: ubuntu-latest

    # 実行する処理＆コマンド指定
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10.14
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.13
      - name: Install dependencies
        run: |
          # pip更新
          python -m pip install --upgrade pip
          pip install requests
          pip install gspread
          pip install google-auth
          pip install numpy
          pip install pandas
         
      - name: Run script
        run: |
          cd ./src
          python refresh.py
          python tiktok_api.py
          python discord_alert.py
